# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import common_pb2 as common__pb2
from . import entity_pb2 as entity__pb2


class EntityReadAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_stream(
        '/data.EntityReadAPI/List',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=entity__pb2.Entity.FromString,
        )
    self.Get = channel.unary_unary(
        '/data.EntityReadAPI/Get',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=entity__pb2.Entity.FromString,
        )


class EntityReadAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EntityReadAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=entity__pb2.Entity.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=entity__pb2.Entity.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.EntityReadAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class EntityWriteAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/data.EntityWriteAPI/Create',
        request_serializer=entity__pb2.Entity.SerializeToString,
        response_deserializer=entity__pb2.Entity.FromString,
        )
    self.Update = channel.unary_unary(
        '/data.EntityWriteAPI/Update',
        request_serializer=entity__pb2.Entity.SerializeToString,
        response_deserializer=entity__pb2.Entity.FromString,
        )


class EntityWriteAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EntityWriteAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=entity__pb2.Entity.FromString,
          response_serializer=entity__pb2.Entity.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=entity__pb2.Entity.FromString,
          response_serializer=entity__pb2.Entity.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.EntityWriteAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
