# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import event_pb2 as event__pb2


class EventAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Publish = channel.unary_unary(
        '/data.EventAPI/Publish',
        request_serializer=event__pb2.Event.SerializeToString,
        response_deserializer=event__pb2.Event.FromString,
        )
    self.List = channel.unary_stream(
        '/data.EventAPI/List',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=event__pb2.Event.FromString,
        )
    self.Get = channel.unary_unary(
        '/data.EventAPI/Get',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=event__pb2.Event.FromString,
        )


class EventAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Publish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=event__pb2.Event.FromString,
          response_serializer=event__pb2.Event.SerializeToString,
      ),
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=event__pb2.Event.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=event__pb2.Event.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.EventAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
