# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='data',
  syntax='proto3',
  serialized_options=b'\n\021com.phisuite.dataB\nEventProtoP\001',
  serialized_pb=b'\n\x0b\x65vent.proto\x12\x04\x64\x61ta\x1a\x19google/protobuf/any.proto\x1a\x0c\x63ommon.proto\"\xb8\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x13\n\x0btransaction\x18\x04 \x01(\t\x12)\n\x07payload\x18\n \x03(\x0b\x32\x18.data.Event.PayloadEntry\x1a\x44\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x32x\n\x08\x45ventAPI\x12#\n\x07Publish\x12\x0b.data.Event\x1a\x0b.data.Event\x12$\n\x04List\x12\r.data.Options\x1a\x0b.data.Event0\x01\x12!\n\x03Get\x12\r.data.Options\x1a\x0b.data.EventB!\n\x11\x63om.phisuite.dataB\nEventProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_EVENT_PAYLOADENTRY = _descriptor.Descriptor(
  name='PayloadEntry',
  full_name='data.Event.PayloadEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.Event.PayloadEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.Event.PayloadEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=247,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='data.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='data.Event.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='data.Event.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='data.Event.transaction', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='data.Event.payload', index=4,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_PAYLOADENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=247,
)

_EVENT_PAYLOADENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_EVENT_PAYLOADENTRY.containing_type = _EVENT
_EVENT.fields_by_name['payload'].message_type = _EVENT_PAYLOADENTRY
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'PayloadEntry' : _reflection.GeneratedProtocolMessageType('PayloadEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_PAYLOADENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:data.Event.PayloadEntry)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:data.Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.PayloadEntry)


DESCRIPTOR._options = None
_EVENT_PAYLOADENTRY._options = None

_EVENTAPI = _descriptor.ServiceDescriptor(
  name='EventAPI',
  full_name='data.EventAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=249,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='data.EventAPI.Publish',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_EVENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='data.EventAPI.List',
    index=1,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_EVENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='data.EventAPI.Get',
    index=2,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_EVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTAPI)

DESCRIPTOR.services_by_name['EventAPI'] = _EVENTAPI

# @@protoc_insertion_point(module_scope)
