# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import common_pb2 as common__pb2
from . import process_pb2 as process__pb2


class ProcessAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.stream_stream(
        '/data.ProcessAPI/Execute',
        request_serializer=process__pb2.Input.SerializeToString,
        response_deserializer=process__pb2.Output.FromString,
        )


class ProcessAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.stream_stream_rpc_method_handler(
          servicer.Execute,
          request_deserializer=process__pb2.Input.FromString,
          response_serializer=process__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.ProcessAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ProcessReadAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_stream(
        '/data.ProcessReadAPI/List',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=process__pb2.Process.FromString,
        )
    self.Success = channel.unary_stream(
        '/data.ProcessReadAPI/Success',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=process__pb2.Process.FromString,
        )
    self.Failure = channel.unary_stream(
        '/data.ProcessReadAPI/Failure',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=process__pb2.Process.FromString,
        )
    self.Get = channel.unary_unary(
        '/data.ProcessReadAPI/Get',
        request_serializer=common__pb2.Options.SerializeToString,
        response_deserializer=process__pb2.Process.FromString,
        )


class ProcessReadAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Success(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Failure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessReadAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=process__pb2.Process.SerializeToString,
      ),
      'Success': grpc.unary_stream_rpc_method_handler(
          servicer.Success,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=process__pb2.Process.SerializeToString,
      ),
      'Failure': grpc.unary_stream_rpc_method_handler(
          servicer.Failure,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=process__pb2.Process.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=common__pb2.Options.FromString,
          response_serializer=process__pb2.Process.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.ProcessReadAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ProcessWriteAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Record = channel.unary_unary(
        '/data.ProcessWriteAPI/Record',
        request_serializer=process__pb2.Process.SerializeToString,
        response_deserializer=process__pb2.Process.FromString,
        )


class ProcessWriteAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Record(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessWriteAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Record': grpc.unary_unary_rpc_method_handler(
          servicer.Record,
          request_deserializer=process__pb2.Process.FromString,
          response_serializer=process__pb2.Process.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data.ProcessWriteAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
